swagger: '2.0'
info:
  version: '1.0'
  title: The Pulper API
host: localhost:4567
basePath: /apps/pulp/api/
schemes:
  - http
paths:
  /books:
    get:
      parameters:
        - in: header
          name: X-API-AUTH
          type: string
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: 'returns an array of book objects'
          schema:
            type: object
            properties:
              books:
                type: array
            required:
              - books
        '401':
           description: 'when X-API-AUTH header is missing or invalid'