# http://editor.swagger.io
# https://swagger.io/docs/specification/about/
swagger: '2.0'
info:
  version: '1.0'
  title: The Pulper API
host: localhost:4567
basePath: /apps/pulp/api/
schemes:
  - http
securityDefinitions:
  # X-API-AUTH: guid
  APIKeyHeader:
    type: apiKey
    in: header
    name: X-API-AUTH
    description: The X-API-AUTH value can be found listed in the Admin page on the GUI
# Global security (applies to all operations):
security:
  - APIKeyHeader: []
paths:
  /books:
    get:
      produces:
        - application/json
      responses:
        '200':
          description: 'returns an array of book objects'
          schema:
            type: object
            properties:
              books:
                type: array
                items:
                  $ref: '#/definitions/BookItem'
                description: 'An array of books, will be empty if there are no books'
            required:
              - books
          examples:
            application/json:
              {
                "books": [
                {
                  "id": "1",
                  "title": "The Man of Bronze",
                  "publicationYear": 1933,
                  "seriesId": "Mar, 1933",
                  "authors": [
                  {
                    "id": "4",
                    "name": "Lester Dent"
                  },
                  {
                    "id": "10",
                    "name": "Kenneth Robeson"
                  }
                  ],
                  "series": {
                    "id": "1",
                    "name": "Doc Savage"
                  },
                  "publisher": {
                    "id": "1",
                    "name": "Street And Smith"
                  }
                }
                ]
              }
        '401':
          $ref: '#/responses/APIUnauthorizedError'
responses:
  APIUnauthorizedError:
    description: X-API-AUTH header is missing or invalid
    schema:
      type: object
      properties:
        errorMessage:
          type: string
          description: 'description of the error, i.e. was the header missing, or was it invalid'
      required:
        - errorMessage
definitions:
  BookItem:
    type: object
    properties:
      id:
        type: string
      title:
        type: string
      publicationYear:
        type: integer
      seriesId:
        type: string
      authors:
        type: array
        items:
          $ref: '#/definitions/AuthorItem'
      series:
        $ref: '#/definitions/SeriesItem'
      publisher:
        $ref: '#/definitions/PublisherItem'
  AuthorItem:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
  SeriesItem:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
  PublisherItem:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
